### ISSUE TITLE
Cover cmd-exclude-prefixes-k8s by integration tests

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-kind#11]
## Description

We've completed `cmd-exclude-prefixes-k8s` and now we can cover the application by integration tests.

## Test scenarios

We need to cover the next scenarios:
1. Verify that `cmd-exclude-prefixes-k8s` can correctly read cluster prefixes from kube-system configmap.
2. Verify that `cmd-exclude-prefixes-k8s` can correctly collect prefixes if configmap from scenario1 is missed.
3. Verify that `cmd-exclude-prefixes-k8s` can correctly read user's prefixes
 3.1. Verify deleting the user's prefixes.
 3.2. Verify updating the user's prefixes.
 3.3. Verify adding the user's prefixes.
4. Verify that `cmd-exclude-prefixes-k8s`  can correctly read prefixes from envs.
  4.1. Verify that `cmd-exclude-prefixes-k8s` is working fine with correct prefixes from envs. 
  4.2. Verify that `cmd-exclude-prefixes-k8s` is failing with incorrect prefixes from envs.
5. Verify collision prefixes collision cases.

## Testing notes

We have not completed tests for nsmgr + nsc yet, and for first step we can collect prefixes into `alpine` pod via shared volume. And check file source via `kubectl cp`, `kubectl exec -ti "pod name" -- cat "path"`.

**Comment by denis-tingajkin** [comment]
@tigrulya-exe  cc

**Comment by Mixaster995** [comment]
closed via https://github.com/networkservicemesh/deployments-k8s/issues/1353
