### ISSUE TITLE
Cover cmd-forwarder-vpp by integration tests for local/remote scenarios

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-kind#12]
We've migrated most of the needed stuff for the forwarder such as nse, nsc, registry. Now can cover https://github.com/networkservicemesh/cmd-forwarder-vppagent by integration of k8s tests.

**Comment by denis-tingajkin** [comment]
@edwarnicke Do you mind if I'll start to do this? Probably I'll need to some patch cmd-forawrder-vppagent.
