### ISSUE TITLE
Determinate and fix issues that makes build red on kind clusters

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-kind#308]
It looks like integration tests with version a973b9a2ad38 is unstable on kind.

## Problem statement
1. Look at changes between latest success run 8e0ae68116e6 and a973b9a2ad38 to determinate a root cause PR.
2. Report the issue.
3. Provide a fix for the issue.

Build link: https://github.com/networkservicemesh/integration-k8s-kind/pull/307

**Comment by glazychev-art** [comment]
A few tests were temporarily disabled:
https://github.com/networkservicemesh/deployments-k8s/pull/2067
https://github.com/networkservicemesh/deployments-k8s/pull/2088
