### ISSUE TITLE
Add Interdomain testing on kind

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/integration-k8s-kind#517]
## Description
Add interdomain testing scenario on ci to `integration-k8s-kind` repository:
1. Add separate job in github ci for testing interdomain
> a. In this job start and configure 3 kind clusters, using last kubernetes version(from secret)
> b. Run Test interdomain suite
2. Run all tests, check that everything passes

**Comment by denis-tingaikin** [comment]
Could you clarify the issue description and title? Thanks.

**Comment by Mixaster995** [comment]
@denis-tingaikin added more detailed description
