### ISSUE TITLE
K8s should know actual status of nsm PODs

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/integration-k8s-kind#7]
## Description

Sometimes fake NSE/NSMGR pods fail because of POD with the registry is deployed, but **registry service is not started**.

## Solution

Add k8s liveness and readiness probes based on grpc health servies.

**Comment by denis-tingajkin** [comment]
@edwarnicke, @haiodo  actually we have grpc health services in all NSM applications. And we could use something like thishttps://github.com/grpc-ecosystem/grpc-health-probe, but the client doesn't have spire...  It looks like we need to create our own spire based grpc health probe client. What do you think?

**Comment by edwarnicke** [comment]
Additonal question... how can we make ourselves more resilient?  Readiness probes and liveliness probes are goodness... but we should not be serializing in our testing on various things starting up in various orders... resilience to failure, not lifecycles, are the answer we seek :)

**Comment by denis-tingajkin** [comment]
@edwarnicke As I understand we do not plan to use probes and we should focus on things to make our applications resistant to connection problems (for example, the server is initializing and the client is already ready). Is it correct?

**Comment by edwarnicke** [comment]
@denis-tingajkin Correct 👍

**Comment by denis-tingajkin** [comment]
Closed by https://github.com/networkservicemesh/integration-k8s-kind/issues/7#issuecomment-679963269
