### ISSUE TITLE
Add IPv6 cluster for kind testing

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-kind#738]
### Description

We need to add kind cluster with ipv6 addresses.

To create it we need to add `networking` to cluster-configuration:
```
...
networking:
  ipFamily: ipv6
...
```

**Comment by glazychev-art** [comment]
**Current state:**

At the moment it seems that this cannot be done. Because github runners **_don't support_** IPv6. That is, after creating an interface with an ipv6 address, we do not have an ipv6 route where to direct this traffic.

We can either wait for ipv6 support or think about NAT64.

**Comment by denis-tingaikin** [comment]
Seems like done
