### ISSUE TITLE
Spec: Advanced integration-k8s repo pipelining

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-kind#9]
Spec doc: https://docs.google.com/document/d/1q77BYcgDMfVCEUfDUUfjHNfMfX_SFtTRci4qn1f7GyM/edit?usp=sharing

**Comment by denis-tingajkin** [comment]
@haiodo , @edwarnicke , @fkautz please take a look and share your thoughts.
